# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.ico"
    keywords: creeper creeperdc creeperdch CREEPERDCH
    backgroundpic : "img/bg.jpg"

Intro:
    name: CREEPERDCH
    slogan: "I hope that someone who has not forgotten his heart will spend the day and night with you."
    HeadButton: Patient

Nav:
    Home_name: HOME
    is_use_categories : true 
    categories_name: CATEGORIES
    is_use_archives : false
    archives_name: ARCHIVES
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/CREEPERDCH
        twitter: https://twitter.com/wwwwyn4240
        facebook: https://www.facebook.com/wwwwyn
        instagram: https://www.instagram.com/creeperdch/
        
    pages:
        ABOUT: 
            link: "/about/"
        # GROUP :
        #     link: "/group/"
        GALLERY :
            link: "/gallery/"
        TAG:
            link: "/tags/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: CREEPERDCH's TECH
    description: Secure, Contain, Protect
    pic_url: /images/me.jpg
    goto_ulr: "https://creeperdch.xyz"

Gallery :
    title: Mr.metro 
    description: Just another fine responsive 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: hopscotch

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: valine
    shortname: CREEPERDCH 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'H78Pg6j0lgmXRgYJayNMsIe3-gzGzoHsz'
       appKey: 'YwHuAUtNNefaFp7HySR7VvuW'
       notify: false
       verify: false
       placeholder: ヾﾉ≧∀≦)o来快活啊!
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: H78Pg6j0lgmXRgYJayNMsIe3-gzGzoHsz
    app_key: YwHuAUtNNefaFp7HySR7VvuW
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML